"""Added chem_name to tri_chem_info with a varying string of 750

Revision ID: 1b77ec97d2d8
Revises: 65d18549c00e
Create Date: 2026-05-28 15:54:08.230243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b77ec97d2d8'
down_revision: Union[str, Sequence[str], None] = '65d18549c00e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tri_chem_info', sa.Column('chem_name', sa.String(length=750), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tri_chem_info', 'chem_name')
    # ### end Alembic commands ###
