"""tri_reporting_form added index to tri_facility_id

Revision ID: 264c2b19a9b9
Revises: 8b29569eaa26
Create Date: 2026-05-07 15:41:27.163133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264c2b19a9b9'
down_revision: Union[str, Sequence[str], None] = '8b29569eaa26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tri_reporting_form_tri_facility_id'), 'tri_reporting_form', ['tri_facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tri_reporting_form_tri_facility_id'), table_name='tri_reporting_form')
    # ### end Alembic commands ###
