"""changed datatype of db_num column tri_facility_db

Revision ID: 5e9f654a8f0c
Revises: c27f46c2cdd2
Create Date: 2026-05-06 14:52:58.567262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9f654a8f0c'
down_revision: Union[str, Sequence[str], None] = 'c27f46c2cdd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tri_facility_db', 'db_num',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tri_facility_db', 'db_num',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
