"""Increased Length of the varying String columns for npdes,rcra,and uic

Revision ID: 821e77667b35
Revises: 5e9f654a8f0c
Create Date: 2026-05-06 15:25:47.083934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821e77667b35'
down_revision: Union[str, Sequence[str], None] = '5e9f654a8f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tri_facility_npdes', 'npdes_num',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.alter_column('tri_facility_rcra', 'rcra_num',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('tri_facility_uic', 'uic_num',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tri_facility_uic', 'uic_num',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('tri_facility_rcra', 'rcra_num',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('tri_facility_npdes', 'npdes_num',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
