"""Added 4 new tables

Revision ID: c27f46c2cdd2
Revises: b68260c5038c
Create Date: 2026-05-06 14:17:47.883832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27f46c2cdd2'
down_revision: Union[str, Sequence[str], None] = 'b68260c5038c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tri_facility_db',
    sa.Column('db_num', sa.Integer(), nullable=False),
    sa.Column('tri_facility_id', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('db_num', 'tri_facility_id')
    )
    op.create_table('tri_facility_npdes',
    sa.Column('asgn_npdes_ind', sa.Boolean(), nullable=True),
    sa.Column('npdes_num', sa.String(length=10), nullable=False),
    sa.Column('tri_facility_id', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('npdes_num', 'tri_facility_id')
    )
    op.create_table('tri_facility_rcra',
    sa.Column('asgn_rcra_ind', sa.Boolean(), nullable=True),
    sa.Column('rcra_num', sa.String(length=15), nullable=False),
    sa.Column('tri_facility_id', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('rcra_num', 'tri_facility_id')
    )
    op.create_table('tri_facility_uic',
    sa.Column('asgn_uic_ind', sa.Boolean(), nullable=True),
    sa.Column('uic_num', sa.String(length=10), nullable=False),
    sa.Column('tri_facility_id', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('uic_num', 'tri_facility_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tri_facility_uic')
    op.drop_table('tri_facility_rcra')
    op.drop_table('tri_facility_npdes')
    op.drop_table('tri_facility_db')
    # ### end Alembic commands ###
